name = "BarringtonTheorem"
version = "0.1.0"
defaultTargets = ["barringtontheorem"]

[[lean_lib]]
name = "BarringtonTheorem"

[[lean_exe]]
name = "barringtontheorem"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "stable"

